#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/downloads/{complete,incomplete} /watch

# copy config
[[ ! -f /config/settings.json ]] && cp \
	/defaults/settings.json /config/settings.json

# copy blocklist-update script
[[ ! -f /config/blocklist-update.sh ]] && cp \
	/defaults/blocklist-update.sh /config/blocklist-update.sh

if [ ! -z "$USER" ] && [ ! -z "$PASS" ]; then
	sed -i '/rpc-authentication-required/c\    "rpc-authentication-required": true,' /config/settings.json
	sed -i "/rpc-username/c\    \"rpc-username\": \"$USER\"," /config/settings.json
	sed -i "/rpc-password/c\    \"rpc-password\": \"$PASS\"," /config/settings.json
fi

sed '/script-torrent-done-enabled/c\    "script-torrent-done-enabled": true,' /config/settings.json > /config/settings.temp && cp /config/settings.temp /config/settings.json
sed '/script-torrent-done-filename/c\    "script-torrent-done-filename": "/scripts/update_plex.sh",' /config/settings.json > /config/settings.temp && cp /config/settings.temp /config/settings.json

# permissions
chown abc:abc \
	/config/settings.json \
	/config/blocklist-update.sh \
	/downloads \
	/downloads/complete \
	/downloads/incomplete \
	/watch \

chown -R abc:abc /scripts

chmod +x /config/blocklist-update.sh
chmod +x /scripts/update_plex.sh
